import imgApi from '/public/images/imgAPI';

const testimonialsData = [
  {
    avatar: imgApi.avatar[0],
    name: '1John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 100,
    y: 150,
  },
  {
    name: '2John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 120,
    y: 100,
  },
  {
    name: '3John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 400,
    y: 40,
  },
  {
    avatar: imgApi.avatar[3],
    name: '4John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 500,
    y: 300,
  },
  {
    avatar: imgApi.avatar[4],
    name: '5John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 270,
    y: 220,
  },
  {
    name: '6John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 100,
    y: 200,
  },
  {
    avatar: imgApi.avatar[6],
    name: '7John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 100,
    y: 40,
  },
  {
    name: '8John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 330,
    y: 100,
  },
  {
    avatar: imgApi.avatar[1],
    name: '9John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 30,
    y: 50,
  },
  {
    avatar: imgApi.avatar[9],
    name: '10John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 400,
    y: 150,
  },
  {
    name: '11John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 480,
    y: 100,
  },
  {
    name: '12John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 250,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: '13John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 150,
    y: 300,
  },
  {
    avatar: imgApi.avatar[7],
    name: '14John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 300,
    y: 140,
  },
  {
    name: '15John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 480,
    y: 280,
  },
  {
    avatar: imgApi.avatar[5],
    name: '16John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 300,
    y: 300,
  },
];

export default testimonialsData;
