name: GitHub Pages Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'output/**'

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./output
        force_orphan: true